<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Validate-Success-AddFundraising</name>
   <tag></tag>
   <elementGuidId>83eb6de3-d3c6-4dab-8401-c1dcffea2baa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/div/div/</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
